adjective1=input("enter a adjective:")
adjective2=input("enter another adjective")
birdtype= input("enter a bird type")
roomtype=input("enter a room in house")
verbpast=input("enter a verb in past")
verb=input("enter a verb")
relativename=input("enter a relative name")
liquid=input("enter a liquid name")
noun=input("enter a noun")
verbing=input("enter a verb ending with ing")
bodypart=input("enter a body part in plural")
pruralnoun=input("enter a prural noun")
verbing2=input("enter a verb endin with ing")
noun2=input("enter a noun:")

print("It was a ",adjective1,", cold november day.")
print(" I woke up to the",adjective2,"smell of",birdtype,"roasting in the",roomtype,"downstairs")
print("I",verbpast,"down the stairs to see if i could help",verb,"the dinner")
print('''my mom said," see if''',relativename,"need a fresh",noun,'''"''')
print("so i caried a tray with glass full of",liquid,"into the",verbing,"room")
print("when i got there, I couldn't believe my",bodypart)
print("there were",pruralnoun,verbing2,"on the",noun2)
